### PR TITLE
Implement method to get world coordinates in PickIntersection

### PR DESCRIPTION
**Pull request by guimcaballero**
I started some work on #9. It's a simple function that transforms the ndc coordinate into world coordinate, and takes in a view and projection matrix. 

I'm not sure if this is the best way to implement it, I'm open to ideas. I just needed something to get going :P.

As a side note, here's what I'm using it for:

bavy

### CODE REVIEW

**Comment by aevyrie** [comment]
Awesome, thank you! I'll have to take a look when I get some time, it's currently a holiday weekend for me. 

I'd like to build on this to add a 3d cursor (small sphere) in world space to help with debug, this might help us figure out the plane issue you found, because we can visualize where those world space intersections are being calculated. I know they are incorrect right now, and it will snap to vertices.

Anyway, that can come later. I'll merge this as soon as I can take a look.

**Comment by guimcaballero** [comment]
Sure thing, no rush! I just wanted to get started with a basic movement system, so I'm making the features I need on the way.

I'm currently building my game with a dependency to my fork, so I can keep working on it while this pr isn't merged.

The 3d cursor seems a great idea for debugging, although I'm not sure what's the best approach. Maybe a system that moves the sphere to the `pick_state.top()` pick world position?

**Comment by aevyrie** [comment]
> Maybe a system that moves the sphere to the pick_state.top() pick world position?

Yep, I think so.

**Review by aevyrie — CHANGES_REQUESTED** [review]
This looks good, thank you!

My only request is that you change the name from `get_pick_world_pos` to `get_pick_coord_world`. I haven't planned out all the function names or anything like that, but I'd like to keep them consistent where possible. This would then match the existing function `get_pick_coord_ndc`.

So you're aware, I'd eventually like to expose this to the user through the PickableMesh component. To guarantee the output world coordinates are correct, this function must be supplied a correct view and projection matrix. The `bevy_mod_picking` plugin already has that information when the user associates a camera with the PickableMesh components, so I should probably figure out a way to use that. 😄

**Comment by guimcaballero** [comment]
Yeah, makes more sense as `get_pick_coord_world`. I've also moved it after `get_pick_coord_ndc`.

And the PickableMesh things sounds good!

**Comment by aevyrie** [comment]
Great, thanks!

**Review by aevyrie — APPROVED** [review]

**Pull request merged**
