### PR TITLE
Bevy 0.12

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
This is blocked by https://github.com/aevyrie/bevy_eventlistener/pull/11 and https://github.com/aevyrie/bevy_mod_raycast/pull/100

**Comment by nametable** [comment]
Found a few problems with the `bevy_sprite_picking` backend in 0.12. Basically `ComputedVisibility` -> `ViewVisibility` and `size()` now returns a `UVec2` instead of a `Vec2`, after fixing those, the sprite backend works for me in 0.12. Here's the changes I made to the backend (@TristanCacqueray I can PR to you or you can just snag the simple changes): https://github.com/nametable/bevy_mod_picking/commit/834d6f2853f86039d5fa4411071dbb327e791b3f

**Comment by TristanCacqueray** [comment]
Thanks @nametable, to be honest, I am only using the backend for ui-navigation.

**Comment by tungtose** [comment]
Tested with **bevy_sprite_picking** backend

**Comment by aevyrie** [comment]
Thanks for the contribution!

**Pull request merged**
